#Execution Environment
#execution_env=local
execution_env=remote

#Grid URL
grid_url=http://localhost:4444

#Application URL
url=https://demowebshop.tricentis.com/

#Browser Configuration
browsername=chrome

#Credentials
validemail=abdullapinjari123@gmail.com
validpassword=Bts*06bangtanarmy

#Waits(in Sec)
pageloadtimeout=5
implictwait=10
