#Valid Login Expected SuccessMsg
expectedHomePageSuccessMsg=Welcome to our store

#Invalid Login Credentials
invalidemail=Leo123@gmail.com
invalidpassword=12345678

#Register Credentials
fistName=Abdulla
lastName=Pinjari
emailAddress=abdullapinjari123@gmail.com
expectedUserAlreadyExistMsg=The specified email already exists

#Search
validProductName=Build your own cheap computer
invalidProductName=Serum
expectedAlertMsg=Please enter some search keyword


















